In [1]:
import torch

In [2]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [4]:
a[2] = 100
a.storage(), b.storage()

( 0
  1
  100
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
  0
  1
  100
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9])

In [5]:
c = b[1:,1:]
c, c.storage_offset(), c.shape

(tensor([[4, 5],
         [7, 8]]),
 4,
 torch.Size([2, 2]))

In [6]:
a = a.to(float)
torch.sqrt_(a)
a

tensor([ 0.0000,  1.0000, 10.0000,  1.7321,  2.0000,  2.2361,  2.4495,  2.6458,
         2.8284], dtype=torch.float64)