Einsum
======

- in pytorch : torch.einsum
- in tensorflow: tf.einsum
- in numpy : numpy.einsum



In [1]:
import torch
import numpy as np

In [2]:
A = np.random.rand(3,5)
B = np.random.rand(5,3)
M = np.empty((3,2))

In [3]:
A

array([[0.06826841, 0.95954256, 0.44293092, 0.91246281, 0.12303518],
       [0.55577359, 0.31399129, 0.71670176, 0.47720299, 0.96542467],
       [0.14732689, 0.62933207, 0.53945064, 0.69247926, 0.47982099]])

In [4]:
B

array([[0.37198692, 0.20420639, 0.65782355],
       [0.59514695, 0.52271201, 0.44465955],
       [0.63975027, 0.51930145, 0.24543627],
       [0.84971599, 0.77621981, 0.25772208],
       [0.65613505, 0.07804591, 0.0437936 ]])

In [5]:
M

array([[4.67994921e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [6]:
for i in range(3):
    for j in range(2):
        total = 0
        for k in range(5):
            total += A[i,k]*B[k,j]
        M[i,j]  = total
        

In [7]:
M

array([[1.7358909 , 1.46339404],
       [1.89105759, 1.09556566],
       [1.6777005 , 1.2141462 ]])

In [8]:
N = np.empty((3,2))

In [9]:
N

array([[1.7358909 , 1.46339404],
       [1.89105759, 1.09556566],
       [1.6777005 , 1.2141462 ]])

In [10]:
N = np.einsum('ik,kj -> ij', A, B)

In [11]:
N

array([[1.7358909 , 1.46339404, 0.82083961],
       [1.89105759, 1.09556566, 0.84638996],
       [1.6777005 , 1.2141462 , 0.70863465]])

In [38]:
a = np.random.randint(5,size=5)
a

array([4, 0, 2, 2, 1])

In [40]:
b = np.random.randint(5,size=3)
b

array([2, 1, 1])

In [41]:
outer = np.einsum('i,j->ij',a,b)
outer

array([[8, 4, 4],
       [0, 0, 0],
       [4, 2, 2],
       [4, 2, 2],
       [2, 1, 1]])

In [15]:
for i in range(5):
    for j in range(3):
        total = 0
        #no loop index
        total += a[i]*b[j]
        outer[i,j] = total

Rules
=====
1) Repeating letters in different inputs means those values will be multiplied and those products will be the output

In [16]:
M = np.einsum('ik,kj->ij',A,B)

2) Omitting a letter means that axis will be summed.

In [17]:
x = np.ones(3)
sum_x = np.einsum('i->',x)
x,sum_x

(array([1., 1., 1.]), 3.0)

3) we can return the unsummed axes in any order.

In [18]:
x = np.random.rand(5,4,3)
res = np.einsum('ijk->kji',x)
x,res, x.shape, res.shape

(array([[[0.61762711, 0.8659931 , 0.32344738],
         [0.2882496 , 0.59037457, 0.98575111],
         [0.90614125, 0.22431024, 0.76094613],
         [0.63187548, 0.52788355, 0.64144903]],
 
        [[0.70894856, 0.67183962, 0.24203727],
         [0.42728761, 0.11395491, 0.22471515],
         [0.34813792, 0.88681942, 0.48111853],
         [0.23586497, 0.39346914, 0.19607143]],
 
        [[0.68126452, 0.4415422 , 0.65290782],
         [0.22112076, 0.94380266, 0.4247724 ],
         [0.71101753, 0.09811658, 0.28287451],
         [0.25321746, 0.09632883, 0.5470502 ]],
 
        [[0.71743983, 0.78425608, 0.13594393],
         [0.57559074, 0.40443666, 0.28114574],
         [0.12225231, 0.60746265, 0.98820248],
         [0.77935123, 0.10759621, 0.40394789]],
 
        [[0.25502549, 0.02743848, 0.86750732],
         [0.40325949, 0.86688796, 0.18320304],
         [0.64349617, 0.9683524 , 0.93085404],
         [0.48568938, 0.80231379, 0.52728886]]]),
 array([[[0.61762711, 0.70894856, 0.68126452,

Vediamo altri esempi

In [19]:
x = torch.rand((2,3))
v = torch.rand((1,3))
x,v

(tensor([[0.4791, 0.2636, 0.0665],
         [0.4449, 0.4341, 0.7383]]),
 tensor([[0.9617, 0.0210, 0.8722]]))

In [20]:
#permutation of Tensors
y= torch.einsum("ij->ji", x)
y

tensor([[0.4791, 0.4449],
        [0.2636, 0.4341],
        [0.0665, 0.7383]])

In [21]:
#Summation (rule num. 2)
y= torch.einsum("ij->", x)
y                

tensor(2.4265)

In [22]:
#Column Sun
y= torch.einsum("ij->j", x)
y

tensor([0.9240, 0.6977, 0.8048])

In [23]:
#Row Sum
y= torch.einsum("ij->i", x)
y

tensor([0.8092, 1.6172])

In [24]:
#Matrix-Vector Multiplication
y= torch.einsum("ij,kj->ik", x,v)
y

tensor([[0.5243],
        [1.0809]])

In [25]:
#Matrix-Matrix Multiplication
y= torch.einsum("ij,kj->ik", x,x) # 2x2: 2x3 X 3x2
y

tensor([[0.3035, 0.3767],
        [0.3767, 0.9314]])

In [26]:
#Dot product first row with first row of matrix
y= torch.einsum("i,i->", x[0],x[0])
y

tensor(0.3035)

In [27]:
#Dot product with matrix
y = torch.einsum("ij,ij->",x,x)
y

tensor(1.2349)

In [28]:
#Hadamard Product (element-wise multiplication)
y = torch.einsum("ij,ij->ij",x,x)
y

tensor([[0.2296, 0.0695, 0.0044],
        [0.1979, 0.1884, 0.5450]])

In [29]:
#Outer Product
a = torch.rand((3))
b = torch.rand((5))

y = torch.einsum("i,j->ij",a,b)
a,b,y

(tensor([0.7053, 0.8597, 0.0363]),
 tensor([0.9417, 0.4200, 0.2121, 0.1386, 0.2081]),
 tensor([[0.6641, 0.2962, 0.1496, 0.0978, 0.1468],
         [0.8095, 0.3610, 0.1824, 0.1192, 0.1789],
         [0.0342, 0.0153, 0.0077, 0.0050, 0.0076]]))

In [30]:
#Batch Matrix Multiplication
a = torch.rand((3,2,5))
b = torch.rand((3,5,3))

y=torch.einsum("ijk,ikl->ijl",a,b)
y

tensor([[[1.2989, 1.5369, 1.3960],
         [0.6965, 1.5093, 1.3104]],

        [[0.5443, 1.4777, 1.7847],
         [0.4836, 0.8814, 1.2252]],

        [[0.5861, 1.4119, 1.7373],
         [0.2792, 0.9608, 0.7165]]])

In [31]:
#Matrix Diagonal

In [32]:
x = torch.rand((3,3))

y=torch.einsum("ii->",x)
x

tensor([[0.3782, 0.9965, 0.5688],
        [0.5463, 0.2894, 0.8289],
        [0.3317, 0.8812, 0.5260]])

Altri aricoli:

- https://rockt.github.io/2018/04/30/einsum
- https://obilaniu6266h16.wordpress.com/2016/02/04/einstein-summation-in-numpy/
- https://ajcr.net/Basic-guide-to-einsum/